repos:
- repo: local
  hooks:
    - id: ruff_format
      name: ruff format
      entry: ruff format --target-version=py311 --force-exclude
      language: system
      types_or: [python, pyi]
      require_serial: true
- repo: local
  hooks:
    - id: ruff_check
      name: ruff check
      entry: ruff check --target-version=py311 --force-exclude
      language: system
      types_or: [python, pyi]
      require_serial: true
- repo: local
  hooks:
    - id: ty
      name: ty
      entry: ty check --force-exclude
      language: system
      types_or: [python, pyi]
      require_serial: true